# Generated by Django 2.0.3 on 2018-05-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0002_contact1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('comment', models.TextField()),
            ],
        ),
    ]
