# Generated by Django 2.0.3 on 2018-05-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0003_comments1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('aadhar', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('donationtype', models.CharField(max_length=200)),
                ('donationamount', models.CharField(max_length=200)),
                ('describe', models.TextField()),
            ],
        ),
    ]
