# Generated by Django 2.0.3 on 2018-05-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0004_donate1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate1',
            name='city',
            field=models.CharField(choices=[('agra', 'Agra'), ('agartala', 'Agartala'), ('bhopal', 'Bhopal'), ('bangalore', 'Bangalore'), ('delhi', 'Delhi'), ('kolkata', 'Kolkata'), ('dehradun', 'Dehradun'), ('lucknow', 'Lucknow'), ('chandigarh', 'Chandigarh'), ('hyderabad', 'Hyderabad'), ('chennai', 'Channei'), ('patna', 'Patna')], max_length=100),
        ),
        migrations.AlterField(
            model_name='donate1',
            name='donationamount',
            field=models.CharField(choices=[('₹500', '₹500'), ('₹1000', '₹1000'), ('₹2000', '₹2000'), ('₹5000', '₹5000'), ('₹10,000', '₹10,000'), ('₹20,000', '₹20,000'), ('₹30,000', '₹30,000'), ('₹40,000', '₹40,000'), ('₹50,000', '₹50,000')], max_length=200),
        ),
        migrations.AlterField(
            model_name='donate1',
            name='donationtype',
            field=models.CharField(choices=[('children', 'Children'), ('disabled', 'Disabled'), ('environment', 'Environment'), ('youth', 'Youth'), ('women', 'Women'), ('education', 'Education'), ('health', 'Health'), ('elderly', 'Elderly'), ('food', 'Food')], max_length=200),
        ),
    ]
