# Generated by Django 2.0.3 on 2018-05-09 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0006_auto_20180509_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate1',
            name='image',
        ),
        migrations.RemoveField(
            model_name='donate1',
            name='timestamp',
        ),
    ]
