# Generated by Django 2.0.3 on 2018-05-09 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0008_donate1_dp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='name',
            new_name='username',
        ),
    ]
